# -*- coding:utf-8 -*-
def entropy(seq):
    AAList = ["A", "C", "G", "T"]
    nucleotide_dict = {'A': 0, 'C': 0, 'G': 0, 'T': 0}

    for i in range(len(seq)):
        if seq[i] in AAList:
            nucleotide_dict[seq[i]] += 1
        else:
            continue
    #print(nucleotide_dict)
    for item in nucleotide_dict.keys():
        nucleotide_dict[item] /= float(len(seq))
    #print(nucleotide_dict)
    sum = 0.0
    for item in nucleotide_dict.keys():
        sum += nucleotide_dict[item]
    #print(sum)
    #print(nucleotide_dict)

    result = []
    for AA in AAList:
        result.append(nucleotide_dict[AA])
    return result, nucleotide_dict

if __name__ == "__main__":
    sequence = "TACTTTTGTGAATTTCATCAACGATGTGGTTAACCATTATAAGTTCTCTATTCACTTTCTCGATTTTTTCGCAATGTTCTAACACTTCACAATAAGACACTTCTATCATCTCATTGTTCTTTTTACGACCTAAATGAGTTGTAACTAACGTTCGTTTTTTTCAAACAATAATTGTTGTCAAAATTTCTTTTTGTCTTAAATTGAAAACGACTCCTTAAATATTGATTGAAATTCACAACAGAACAATCACTACGTCCAATAGGATCAAATAGACTAGGACCATTACTTTACTAATTAACCTAGTATAGTTTTTTATTCCTCTATTCTTAGCTTCAATAATTACCAGGATCACGTAATTACACACCTAACTAGTGATCACCAAAATTTTGTTGTGGTGAAAACAAAAATCCAAAAAATTCAGTGTTTGTTTTAGTCGAGTTTTTAATAAATTCATGGATAGTTTTAGTCTTTTCGTGATAGCAAAAAAAACTTCGTCACGTATCCAATCTTTTATGAAATCTTTGACACTTTTTACAAAAATTTTTGTTACTGCAAAAATATCCTTCTCTTAATTGATTCAATGTACTTAGTGTAATAACTAAATTGTGGTCACTTTTGTGAAATGGACTGTAGTGAAATTTTCCTCTTAAACATTAACAATAACTATTAGTTTTATAATTAGTGGTTTGTAATAGAAGGTTAGTTATGAATCATATACTTTATTTCTTCAATTACCTATAACCACAATTCAATTTTCTACGTACGTTAATAAATCGATTTTTTTACGTAAATTTTAGTTCATACGAGATATGTGAAAAGGTACTTTCATAAATT"
    nus, entropyDict = entropy(sequence)
    print(nus)